import {
  Bill,
  BillSummary,
  Audit,
  AuditFinding,
  EvidenceRecord,
  Notification,
  FinancialRiskAssessment,
  StressScenarioResult,
  VaRResult,
  ModelRiskResult,
  User,
} from "@/types";

export const MOCK_USER: User = {
  id: "usr-demo-patient-001",
  email: "patient.rahul@curaveris.ai",
  full_name: "Rahul Sharma",
  phone_number: "+91 98765 43210",
  phone_verified: true,
  email_verified: true,
  role: "patient",
  is_active: true,
  dpdp_consent_given: true,
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
};

export const MOCK_BILLS: Bill[] = [
  {
    id: "bill-cv-101",
    user_id: "usr-demo-patient-001",
    reference_number: "CV-2026-8910",
    hospital_name: "Fortis Escorts Heart Institute",
    patient_name: "Amit Sharma",
    admission_date: "2026-08-12",
    discharge_date: "2026-08-16",
    total_billed_amount: 385000,
    bill_type: "INPATIENT_DISCHARGE",
    insurance_type: "TPA Cashless / Star Health",
    processing_status: "COMPLETED",
    processing_job_id: "job-audit-8910",
    processing_started_at: "2026-08-16T10:00:00Z",
    processing_completed_at: "2026-08-16T10:01:14Z",
    retry_count: 0,
    file_name_original: "Fortis_Angioplasty_Discharge_Bill_Final.pdf",
    file_size_bytes: 3450000,
    file_mime_type: "application/pdf",
    created_at: "2026-08-16T09:58:00Z",
    updated_at: "2026-08-16T10:01:14Z",
    line_items: [
      {
        id: "li-101-1",
        item_sequence: 1,
        raw_description: "Drug Eluting Stent (DES) Resolute Onyx 3.0x24mm",
        normalized_name: "Drug Eluting Stent (DES)",
        category: "CARDIAC_IMPLANT",
        quantity: 1,
        unit_price: 65000,
        total_price: 65000,
        gst_rate_applied: 5,
        extraction_confidence: 0.99,
        page_number: 1,
      },
      {
        id: "li-101-2",
        item_sequence: 2,
        raw_description: "ICU Daily Nursing & Vital Charting (4 Days)",
        normalized_name: "ICU Nursing Charges",
        category: "BED_CHARGES",
        quantity: 4,
        unit_price: 4500,
        total_price: 18000,
        gst_rate_applied: 0,
        extraction_confidence: 0.98,
        page_number: 2,
      },
      {
        id: "li-101-3",
        item_sequence: 3,
        raw_description: "Meropenem 1g IV Infusion (12 Vials)",
        normalized_name: "Meropenem 1g Injection",
        category: "PHARMACEUTICALS",
        quantity: 12,
        unit_price: 2450,
        total_price: 29400,
        gst_rate_applied: 12,
        extraction_confidence: 0.97,
        page_number: 2,
      },
      {
        id: "li-101-4",
        item_sequence: 4,
        raw_description: "Unbundled PPE & Surgical Consumable Kit",
        normalized_name: "Surgical Consumables Kit",
        category: "CONSUMABLES",
        quantity: 4,
        unit_price: 1825,
        total_price: 7300,
        gst_rate_applied: 5,
        extraction_confidence: 0.95,
        page_number: 3,
      },
      {
        id: "li-101-5",
        item_sequence: 5,
        raw_description: "Coronary Angiography & Cath Lab Suite Facility",
        normalized_name: "Cath Lab Procedure Fee",
        category: "PROCEDURE",
        quantity: 1,
        unit_price: 165000,
        total_price: 165000,
        gst_rate_applied: 0,
        extraction_confidence: 0.99,
        page_number: 1,
      },
      {
        id: "li-101-6",
        item_sequence: 6,
        raw_description: "Physician & Intensivist Consultation Visits",
        normalized_name: "Doctor Consultation",
        category: "PROFESSIONAL_FEES",
        quantity: 8,
        unit_price: 2500,
        total_price: 20000,
        gst_rate_applied: 0,
        extraction_confidence: 0.99,
        page_number: 3,
      },
    ],
  },
  {
    id: "bill-cv-102",
    user_id: "usr-demo-patient-001",
    reference_number: "CV-2026-8911",
    hospital_name: "Apollo Hospitals, Bannerghatta Road",
    patient_name: "Meera Nair",
    admission_date: "2026-08-05",
    discharge_date: "2026-08-09",
    total_billed_amount: 290000,
    bill_type: "INPATIENT_DISCHARGE",
    insurance_type: "HDFC ERGO Health",
    processing_status: "COMPLETED",
    processing_job_id: "job-audit-8911",
    processing_started_at: "2026-08-09T14:00:00Z",
    processing_completed_at: "2026-08-09T14:01:05Z",
    retry_count: 0,
    file_name_original: "Apollo_Total_Knee_Replacement_Bill.pdf",
    file_size_bytes: 2890000,
    file_mime_type: "application/pdf",
    created_at: "2026-08-09T13:50:00Z",
    updated_at: "2026-08-09T14:01:05Z",
  },
  {
    id: "bill-cv-103",
    user_id: "usr-demo-patient-001",
    reference_number: "CV-2026-8912",
    hospital_name: "Max Super Speciality Hospital, Saket",
    patient_name: "Sanjay Verma",
    admission_date: "2026-07-28",
    discharge_date: "2026-08-02",
    total_billed_amount: 175000,
    bill_type: "INPATIENT_DISCHARGE",
    insurance_type: "Care Health Insurance",
    processing_status: "COMPLETED",
    processing_job_id: "job-audit-8912",
    processing_started_at: "2026-08-02T11:00:00Z",
    processing_completed_at: "2026-08-02T11:00:45Z",
    retry_count: 0,
    file_name_original: "Max_ICU_Pneumonia_Treatment_Bill.pdf",
    file_size_bytes: 1980000,
    file_mime_type: "application/pdf",
    created_at: "2026-08-02T10:45:00Z",
    updated_at: "2026-08-02T11:00:45Z",
  },
  {
    id: "bill-cv-104",
    user_id: "usr-demo-patient-001",
    reference_number: "CV-2026-8913",
    hospital_name: "Manipal Hospital, Old Airport Road",
    patient_name: "Kavita Reddy",
    admission_date: "2026-07-15",
    discharge_date: "2026-07-17",
    total_billed_amount: 120000,
    bill_type: "DAYCARE_SURGERY",
    insurance_type: "Self Pay",
    processing_status: "COMPLETED",
    processing_job_id: "job-audit-8913",
    processing_started_at: "2026-07-17T16:00:00Z",
    processing_completed_at: "2026-07-17T16:00:50Z",
    retry_count: 0,
    file_name_original: "Manipal_Laparoscopic_Surgery_Bill.pdf",
    file_size_bytes: 1450000,
    file_mime_type: "application/pdf",
    created_at: "2026-07-17T15:30:00Z",
    updated_at: "2026-07-17T16:00:50Z",
  },
];

export const MOCK_BILL_SUMMARIES: BillSummary[] = [
  {
    id: "bill-cv-101",
    hospital_name: "Fortis Escorts Heart Institute",
    patient_name: "Amit Sharma",
    admission_date: "2026-08-12",
    discharge_date: "2026-08-16",
    total_billed_amount: 385000,
    total_overcharge: 47800,
    processing_status: "COMPLETED",
    file_name_original: "Fortis_Angioplasty_Discharge_Bill_Final.pdf",
    created_at: "2026-08-16T09:58:00Z",
  },
  {
    id: "bill-cv-102",
    hospital_name: "Apollo Hospitals, Bannerghatta Road",
    patient_name: "Meera Nair",
    admission_date: "2026-08-05",
    discharge_date: "2026-08-09",
    total_billed_amount: 290000,
    total_overcharge: 36200,
    processing_status: "COMPLETED",
    file_name_original: "Apollo_Total_Knee_Replacement_Bill.pdf",
    created_at: "2026-08-09T13:50:00Z",
  },
  {
    id: "bill-cv-103",
    hospital_name: "Max Super Speciality Hospital, Saket",
    patient_name: "Sanjay Verma",
    admission_date: "2026-07-28",
    discharge_date: "2026-08-02",
    total_billed_amount: 175000,
    total_overcharge: 22400,
    processing_status: "COMPLETED",
    file_name_original: "Max_ICU_Pneumonia_Treatment_Bill.pdf",
    created_at: "2026-08-02T10:45:00Z",
  },
  {
    id: "bill-cv-104",
    hospital_name: "Manipal Hospital, Old Airport Road",
    patient_name: "Kavita Reddy",
    admission_date: "2026-07-15",
    discharge_date: "2026-07-17",
    total_billed_amount: 120000,
    total_overcharge: 14800,
    processing_status: "COMPLETED",
    file_name_original: "Manipal_Laparoscopic_Surgery_Bill.pdf",
    created_at: "2026-07-17T15:30:00Z",
  },
];

export const MOCK_FINDINGS_101: AuditFinding[] = [
  {
    id: "find-101-1",
    audit_id: "aud-cv-101",
    bill_line_item_id: "li-101-1",
    finding_type: "NPPA_STATUTORY_CAP_BREACH",
    finding_source: "DETERMINISTIC",
    severity: "CRITICAL",
    item_description: "Drug Eluting Stent (DES) Resolute Onyx 3.0x24mm",
    billed_amount: 65000,
    benchmark_amount: 30080,
    overcharge_amount: 22500,
    statutory_reference: "NPPA Notification S.O. 1331(E) / Gazette Order 2023",
    legal_basis: "Mandatory statutory price ceiling under DPCO 2013 paragraph 19. Hospitals cannot charge more than ₹30,080 (+GST) for any DES coronary stent.",
    user_explanation: "The hospital charged ₹65,000 for a cardiac drug-eluting stent. Under official NPPA price control orders, the maximum allowed ceiling is ₹30,080. You were overcharged ₹22,500 on this single item.",
    is_disputable: true,
    ml_confidence: 0.99,
    created_at: "2026-08-16T10:01:00Z",
  },
  {
    id: "find-101-2",
    audit_id: "aud-cv-101",
    bill_line_item_id: "li-101-2",
    finding_type: "ICU_PACKAGE_UNBUNDLING",
    finding_source: "DETERMINISTIC",
    severity: "HIGH",
    item_description: "ICU Daily Nursing & Vital Charting (4 Days @ ₹4,500/day)",
    billed_amount: 18000,
    benchmark_amount: 0,
    overcharge_amount: 18000,
    statutory_reference: "CGHS Inpatient Package Guidelines Clause 4.2 & NHA Rules",
    legal_basis: "ICU daily room tariff is all-inclusive of resident nursing, monitoring, and charting. Separate billing of nursing care violates standardized clinical package norms.",
    user_explanation: "The hospital billed ₹18,000 for ICU nursing as a separate line item. Under standard healthcare guidelines, nursing care is already included in the ICU bed tariff.",
    is_disputable: true,
    ml_confidence: 0.98,
    created_at: "2026-08-16T10:01:05Z",
  },
  {
    id: "find-101-3",
    audit_id: "aud-cv-101",
    bill_line_item_id: "li-101-3",
    finding_type: "DPCO_NLEM_PRICE_CEILING",
    finding_source: "DETERMINISTIC",
    severity: "HIGH",
    item_description: "Meropenem 1g IV Infusion (12 Vials @ ₹2,450 vs Cap ₹950)",
    billed_amount: 29400,
    benchmark_amount: 11400,
    overcharge_amount: 4500,
    statutory_reference: "DPCO 2013 National List of Essential Medicines (NLEM) Schedule I",
    legal_basis: "Meropenem 1g injection is a regulated NLEM schedule formulation with a fixed ceiling price of ₹950 per vial.",
    user_explanation: "12 vials of Meropenem 1g injection were billed at ₹2,450 per vial instead of the government price cap of ₹950. Total recoverable excess is ₹4,500.",
    is_disputable: true,
    ml_confidence: 0.96,
    created_at: "2026-08-16T10:01:10Z",
  },
  {
    id: "find-101-4",
    audit_id: "aud-cv-101",
    bill_line_item_id: "li-101-4",
    finding_type: "CONSUMABLES_IRDAI_DISPUTE",
    finding_source: "ML",
    severity: "MEDIUM",
    item_description: "Unbundled PPE & Surgical Consumable Kits",
    billed_amount: 7300,
    benchmark_amount: 4500,
    overcharge_amount: 2800,
    statutory_reference: "IRDAI Master Circular on Non-Payable Items Ref IRDA/HLT/REG/2020",
    legal_basis: "General surgical consumables and PPE kits unbundled beyond clinical consumption limits.",
    user_explanation: "Surgical consumables were billed 4 times the standard procedure requirement. Deductible amount ₹2,800 is recoverable.",
    is_disputable: true,
    ml_confidence: 0.92,
    created_at: "2026-08-16T10:01:12Z",
  },
];

export const MOCK_AUDIT_101: Audit = {
  id: "aud-cv-101",
  bill_id: "bill-cv-101",
  user_id: "usr-demo-patient-001",
  audit_version: "2.4.0",
  statutory_ref_version: "NPPA-DPCO-2026-Q3",
  ml_model_version: "curaveris-forensic-v3.1",
  total_billed: 385000,
  total_overcharge_deterministic: 45000,
  total_overcharge_ml_estimate: 2800,
  risk_score: 84,
  risk_label: "HIGH",
  uncertainty_lower: 42000,
  uncertainty_upper: 51000,
  shadow_bill_detected: true,
  finding_count: 4,
  finding_summary: {
    CRITICAL: 1,
    HIGH: 2,
    MEDIUM: 1,
    LOW: 0,
  },
  findings: MOCK_FINDINGS_101,
  shap_values: [
    {
      feature_label: "DES Stent Price Cap Violation (NPPA 2023)",
      shap_value: 0.46,
      direction: "INCREASES_RISK",
      explanation: "Billed at ₹65,000 vs statutory ceiling of ₹30,080",
    },
    {
      feature_label: "ICU Nursing Unbundling (CGHS Rule)",
      shap_value: 0.32,
      direction: "INCREASES_RISK",
      explanation: "Billed separately despite being bundled in ICU room tariff",
    },
    {
      feature_label: "NLEM Medicine Margin Markup (DPCO)",
      shap_value: 0.14,
      direction: "INCREASES_RISK",
      explanation: "Antibiotic billed above published price ceiling",
    },
    {
      feature_label: "Hospital NABH Accreditation Tier",
      shap_value: -0.08,
      direction: "DECREASES_RISK",
      explanation: "Standard hospital accreditation verified",
    },
  ],
  recommendations: [
    {
      title: "File Section 65B Formal Dispute with Hospital Grievance Cell",
      description: "Send the auto-generated legal demand notice citing NPPA Order S.O. 1331(E) requesting immediate refund of ₹47,800 within 7 days.",
      priority: "URGENT",
    },
    {
      title: "Submit TPA Insurance Reconciliation Appeal",
      description: "Attach the forensic report to your insurer to reverse unfair non-payable deductions.",
      priority: "HIGH",
    },
    {
      title: "Escalate to District Consumer Commission / NPPA Portal",
      description: "If the hospital fails to refund within 15 days, one-click export the petition to the National Consumer Helpline and IPDMS portal.",
      priority: "NORMAL",
    },
  ],
  completed_at: "2026-08-16T10:01:14Z",
};

export const MOCK_EVIDENCE_101: EvidenceRecord = {
  id: "ev-cv-101",
  bill_id: "bill-cv-101",
  audit_id: "aud-cv-101",
  merkle_root: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  hmac_signature: "7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
  canonical_payload: {
    bill_id: "bill-cv-101",
    hospital_name: "Fortis Escorts Heart Institute",
    total_billed: 385000,
    total_overcharge: 47800,
    statutory_citations: [
      "NPPA Order S.O. 1331(E)",
      "DPCO 2013 Paragraph 19",
      "CGHS Clause 4.2",
    ],
    timestamp: "2026-08-16T10:01:14.000Z",
    evidence_act_clause: "Section 65B (Indian Evidence Act / BSA 2023)",
  },
  leaf_hashes: [
    "c4ca4238a0b923820dcc509a6f75849b",
    "c81e728d9d4c2f636f067f89cc14862c",
    "eccbc87e4b5ce2fe28308fd9f2a7baf3",
  ],
  certificate_url: "/api/v1/bills/bill-cv-101/evidence/certificate.pdf",
  issued_at: "2026-08-16T10:01:14Z",
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-001",
    user_id: "usr-demo-patient-001",
    event_type: "AUDIT_COMPLETED",
    title: "Bill Audit Complete: ₹47,800 Overcharge Found",
    body: "Your inpatient bill from Fortis Escorts Heart Institute has been audited. 4 statutory violations were detected.",
    priority: "HIGH",
    entity_type: "AUDIT",
    entity_id: "bill-cv-101",
    is_read: false,
    link: "/bills/bill-cv-101/audit",
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: "notif-002",
    user_id: "usr-demo-patient-001",
    event_type: "EVIDENCE_SEALED",
    title: "Section 65B Electronic Certificate Generated",
    body: "Tamper-evident SHA-256 legal certificate is sealed and ready for formal grievance submission.",
    priority: "NORMAL",
    entity_type: "DISPUTE",
    entity_id: "bill-cv-101",
    is_read: false,
    link: "/bills/bill-cv-101/audit",
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
  {
    id: "notif-003",
    user_id: "usr-demo-patient-001",
    event_type: "STATUTORY_UPDATE",
    title: "New NPPA Price Cap Notification Published",
    body: "NPPA published revised ceiling limits for orthopaedic and cardiac implants for Q3 2026.",
    priority: "LOW",
    entity_type: null,
    entity_id: null,
    is_read: true,
    link: "/compliance",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const MOCK_FRM_101: FinancialRiskAssessment = {
  id: "frm-cv-101",
  bill_id: "bill-cv-101",
  audit_id: "aud-cv-101",
  user_id: "usr-demo-patient-001",
  monthly_income: 95000,
  monthly_expenses: 45000,
  verified_savings: 180000,
  insurance_coverage_claimed: 300000,
  already_paid: 85000,
  ead: 85000,
  pd: 0.06,
  lgd: 0.56,
  expected_loss: 4760,
  lcr: 2.12,
  var_90: 14200,
  var_95: 18500,
  cvar_95: 24200,
  mc_sample_count: 10000,
  worst_case_el: 32000,
  worst_case_lcr: 1.15,
  requires_human_review: false,
  model_risk_level: "LOW",
  frm_engine_version: "curaveris-frm-v3.1",
  computed_at: "2026-08-16T10:02:00Z",
  created_at: "2026-08-16T10:02:00Z",
  updated_at: "2026-08-16T10:02:00Z",
  financial_recommendations: [
    {
      priority: 1,
      action: "Immediate recovery of ₹47,800 overcharge restores emergency household buffer to 4.2 months.",
      rationale: "Statutory NPPA DES cap breach provides immediate refund claim ground.",
    },
    {
      priority: 2,
      action: "Submit IRDAI dispute letter to prevent ₹37,200 out-of-pocket insurance deduction.",
      rationale: "Non-payable consumables disputed with official circular.",
    },
  ],
};

