apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: curaveris-ingress
  namespace: curaveris
  labels:
    app.kubernetes.io/name: curaveris
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  tls:
    - hosts:
        - curaveris.in
        - app.curaveris.in
      secretName: curaveris-tls-cert
  rules:
    - host: curaveris.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: curaveris-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: curaveris-web
                port:
                  number: 3000
    - host: app.curaveris.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: curaveris-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: curaveris-web
                port:
                  number: 3000
